# Generated by Django 2.0.6 on 2018-07-15 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.BigIntegerField()),
                ('bits_rotated', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30)),
                ('guid', models.CharField(max_length=36)),
                ('source', models.CharField(max_length=30)),
                ('bits_differ', models.IntegerField(blank=True, null=True)),
                ('hash', models.BigIntegerField()),
                ('nearest_duplicate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearest_reverse', to='simhash_django.SimHash')),
            ],
        ),
        migrations.AddField(
            model_name='permutation',
            name='sim_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permutations', to='simhash_django.SimHash'),
        ),
        migrations.AlterUniqueTogether(
            name='simhash',
            unique_together={('guid', 'source', 'method')},
        ),
    ]
